program: simple_sweep_test.py
method: grid
metric:
  name: avg_mask_value
  goal: minimize
parameters:
  tau:
    values: [0.01, 0.02, 0.05, 0.1]
  threshold:
    values: [0.3, 0.5, 0.7]
  improved_masking:
    values: [true, false]
  beta:
    values: [2.0, 5.0, 10.0]