program: sweep_agent.py
method: grid
metric:
  name: perplexity
  goal: minimize
parameters:
  tau:
    values: [0.01, 0.02, 0.05, 0.1]
  improved_masking:
    values: [true, false]
  beta:
    values: [2.0, 5.0, 10.0]
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--sweep_id=${sweep_id}"
  - "--project=pdp-gpt2-sweep"